# fly.toml app configuration file generated for thisissantidev on 2023-08-01T15:21:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thisissantidev"
primary_region = "qro"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
