# fly.toml app configuration file generated for this-is-santi-dev on 2023-07-30T21:58:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "this-is-santi-dev"
primary_region = "qro"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
